// lib/season/h2h.ts
// H2H (head-to-head) scoring for weekly matchups.
//
// In H2H mode each team plays exactly one opponent per scoring period (generated by
// generateMatchups() in lib/scoring/matchups.ts, which is also used for VP mode).
// Scoring is simple: the team with more FP wins the matchup. No rank-based VP bonuses.
//
// scoreH2hWeek() mirrors scoreVpWeek() in structure but writes only homeScore/awayScore
// (not homeVP/awayVP). computeH2hStandings() derives W-L-T from those cached scores.

import type { PrismaClient } from "@prisma/client";
import type { ScoringPeriod } from "@/lib/scoring/periods";
import { computeAllTeamScores } from "@/lib/scoring/matchups";
import { parseScoringSettings } from "@/lib/scoring/settings";
import type { VpStanding } from "@/lib/scoring/vp";

// Score all H2H matchups for one week.
// Computes each team's FP once, writes homeScore/awayScore to every Matchup row.
// homeVP / awayVP are left null — H2H leagues do not use VP.
export async function scoreH2hWeek(
  leagueId: string,
  week: number,
  period: ScoringPeriod,
  prisma: PrismaClient
): Promise<void> {
  const league = await prisma.fantasyLeague.findUniqueOrThrow({
    where: { id: leagueId },
    select: { scoringSettings: true },
  });
  const settings = parseScoringSettings(league.scoringSettings);

  // Beta/replay leagues store period dates at remapped real-calendar times for lifecycle
  // detection, but actual stat lines live at the original fixture dates. Translate back
  // before querying scores so the stat line query finds real data.
  const rawSettings = league.scoringSettings as Record<string, unknown>;
  const betaWeekMappings = rawSettings?.betaWeekMappings as
    | { week: number; fixtureStart: string; fixtureEnd: string }[]
    | undefined;
  const fixtureMapping = betaWeekMappings?.find((m) => m.week === week);
  const scoringPeriod: ScoringPeriod = fixtureMapping
    ? { week, startsAt: new Date(fixtureMapping.fixtureStart), endsAt: new Date(fixtureMapping.fixtureEnd) }
    : period;

  const scores = await computeAllTeamScores(leagueId, scoringPeriod, settings, prisma);

  const matchups = await prisma.matchup.findMany({
    where: { leagueId, week, isPlayoff: false },
    select: { id: true, homeTeamId: true, awayTeamId: true },
  });

  for (const m of matchups) {
    await prisma.matchup.update({
      where: { id: m.id },
      data: {
        homeScore: scores.get(m.homeTeamId) ?? null,
        awayScore: scores.get(m.awayTeamId) ?? null,
        // homeVP / awayVP intentionally left null for H2H mode
      },
    });
  }
}

// Compute H2H standings from scored matchup rows.
// Returns the same VpStanding shape as computeVpStandings() so downstream consumers
// (standings-service.ts, standings page) work without changes.
// totalVP is repurposed as "wins × 2 + ties × 1" for a points-table sort consistent
// with W-L-T display. No VP bonuses exist in H2H mode.
export function computeH2hStandings(
  teams: Array<{ id: string; name: string }>,
  matchups: Array<{
    homeTeamId: string;
    awayTeamId: string;
    homeScore: number | null;
    awayScore: number | null;
    isPlayoff: boolean;
  }>
): VpStanding[] {
  const byTeam = new Map<string, VpStanding>();
  for (const t of teams) {
    byTeam.set(t.id, {
      fantasyTeamId: t.id,
      teamName: t.name,
      totalVP: 0,   // used as points (W=2, T=1) for sort purposes
      matchupVP: 0, // wins
      rankVP: 0,    // ties
      wins: 0,
      losses: 0,
      ties: 0,
      pointsFor: 0,
    });
  }

  const regularMatchups = matchups.filter(
    (m) => !m.isPlayoff && m.homeScore !== null && m.awayScore !== null
  );

  for (const m of regularMatchups) {
    const home = byTeam.get(m.homeTeamId);
    const away = byTeam.get(m.awayTeamId);
    if (!home || !away) continue;

    const hs = m.homeScore!;
    const as = m.awayScore!;

    home.pointsFor += hs;
    away.pointsFor += as;

    if (hs > as) {
      home.wins++;
      home.matchupVP++;
      home.totalVP += 2;
      away.losses++;
    } else if (as > hs) {
      away.wins++;
      away.matchupVP++;
      away.totalVP += 2;
      home.losses++;
    } else {
      home.ties++;
      home.rankVP++;
      home.totalVP += 1;
      away.ties++;
      away.rankVP++;
      away.totalVP += 1;
    }
  }

  // Sort: wins (points desc) → pointsFor (tiebreaker)
  return [...byTeam.values()].sort((a, b) => {
    if (b.totalVP !== a.totalVP) return b.totalVP - a.totalVP;
    if (b.wins !== a.wins) return b.wins - a.wins;
    return b.pointsFor - a.pointsFor;
  });
}
