// Shared style tokens for draft room components.
// Centralised here so PickBoard, PlayerPanel, and NeedsPanel can import without
// creating a circular dependency back to DraftRoom.tsx.
export const styles = {
  root: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column" as const,
  },
  topBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 24px",
    height: 52,
    background: "rgba(10,14,26,0.92)",
    backdropFilter: "blur(14px)",
    borderBottom: "1px solid var(--border)",
    flexShrink: 0,
    position: "sticky" as const,
    top: 0,
    zIndex: 50,
    gap: 12,
  },
  clock: {
    fontSize: 22,
    fontWeight: 700,
    fontVariantNumeric: "tabular-nums",
    fontFamily: "var(--font-stats)",
    border: "2px solid",
    borderRadius: 8,
    padding: "2px 10px",
    minWidth: 58,
    textAlign: "center" as const,
    transition: "color 0.3s, border-color 0.3s",
  },
  btnPrimary: {
    background: "var(--accent)",
    color: "var(--accent-ink)",
    border: "none",
    borderRadius: 6,
    padding: "7px 16px",
    fontWeight: 600,
    fontSize: 13,
  },
  btnSecondary: {
    background: "rgba(150,160,200,0.08)",
    color: "var(--text)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "6px 12px",
    fontSize: 13,
  },
  btnPick: {
    background: "var(--green)",
    color: "#000",
    border: "none",
    borderRadius: 5,
    minHeight: 44,
    padding: "0 14px",
    fontWeight: 700,
    fontSize: 12,
    cursor: "pointer" as const,
  },
  queueBtn: {
    background: "transparent",
    color: "var(--muted)",
    border: "1px solid var(--border)",
    borderRadius: 4,
    minHeight: 44,
    minWidth: 44,
    fontSize: 11,
    cursor: "pointer" as const,
  },
  starBtn: {
    background: "transparent",
    border: "none",
    minHeight: 44,
    minWidth: 44,
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    fontSize: 15,
    lineHeight: 1,
    color: "var(--accent)",
    cursor: "pointer" as const,
  },
  tab: {
    border: "none",
    borderRadius: 999,
    padding: "5px 14px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer" as const,
  },
  body: {
    flex: 1,
    display: "flex",
    gap: 0,
    overflow: "hidden",
  },
  leftCol: {
    width: 300,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 16,
    padding: "20px 16px 24px",
    borderRight: "1px solid var(--border)",
    overflowY: "auto" as const,
  },
  centerCol: {
    flex: 1,
    padding: "20px 20px 24px",
    overflowY: "auto" as const,
    borderRight: "1px solid var(--border)",
    display: "flex" as const,
    flexDirection: "column" as const,
    gap: 16,
    minWidth: 0,
  },
  rightCol: {
    width: 260,
    flexShrink: 0,
    padding: "20px 16px 24px",
    overflowY: "auto" as const,
    display: "flex" as const,
    flexDirection: "column" as const,
    gap: 16,
  },
  card: {
    background: "var(--card)",
    border: "1px solid var(--border)",
    borderRadius: 16,
    padding: "18px 20px",
  },
  cardTitle: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase" as const,
    color: "var(--muted)",
    marginBottom: 16,
  },
  table: {
    borderCollapse: "collapse" as const,
    width: "100%",
  },
  th: {
    textAlign: "left" as const,
    padding: "4px 6px",
    fontWeight: 700,
    fontSize: 11,
    letterSpacing: "0.06em",
    color: "var(--faint)",
    textTransform: "uppercase" as const,
  },
  roundLabel: {
    fontSize: 11,
    color: "var(--dim)",
    paddingRight: 8,
    whiteSpace: "nowrap" as const,
    fontWeight: 600,
    fontFamily: "var(--font-stats)",
  },
  pickCell: {
    width: 48,
    height: 38,
    textAlign: "center" as const,
    borderRadius: 4,
    padding: "2px 2px",
    cursor: "default",
  },
  recentRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "10px 12px",
    borderRadius: 8,
    background: "rgba(150,160,200,0.04)",
    marginBottom: 4,
    fontSize: 12,
  },
  playerRow: {
    borderBottom: "1px solid var(--border)",
    cursor: "pointer",
  },
  yourPickBanner: {
    background: "var(--accent)",
    color: "var(--accent-ink)",
    borderRadius: 6,
    padding: "8px 14px",
    fontWeight: 600,
    fontSize: 13,
    textAlign: "center" as const,
  },
  errorBannerContainer: {
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    gap: 12,
    background: "rgba(120, 40, 40, 0.6)",
    color: "var(--red)",
    padding: "10px 20px",
    fontSize: 13,
    borderBottom: "1px solid rgba(248, 113, 113, 0.4)",
  },
  errorBanner: {
    flex: 1,
  },
  errorDismiss: {
    background: "transparent",
    border: "none",
    color: "var(--red)",
    fontSize: 18,
    cursor: "pointer" as const,
    padding: 0,
    lineHeight: 1,
    width: 28,
    height: 28,
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    opacity: 0.7,
    transition: "opacity 0.2s",
  },
  completeBanner: {
    background: "rgba(81,216,138,0.08)",
    color: "var(--green)",
    padding: "8px 20px",
    fontSize: 13,
    borderBottom: "1px solid rgba(81,216,138,0.2)",
  },
  pendingBanner: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: 12,
    background: "var(--accent-dim)",
    color: "var(--accent-strong)",
    padding: "10px 20px",
    fontSize: 13,
    borderBottom: "1px solid var(--accent-border)",
  },
  pausedBanner: {
    background: "rgba(249,115,22,0.12)",
    color: "var(--clock-warn)",
    padding: "8px 20px",
    fontSize: 13,
    borderBottom: "1px solid var(--clock-warn)",
  },
  input: {
    flex: 1,
    background: "rgba(150,160,200,0.06)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    padding: "6px 10px",
    color: "var(--text)",
    outline: "none",
    width: "100%",
    fontSize: 13,
  },
};
